### ISSUE TITLE
Sort by updated date ascending

### ISSUE THREAD

**Issue by tinydylan** [metorikhq/metorik-helper#100] opened 2020-07-03 00:32 UTC
The SQL queries should sort by updated date ascending, to avoid issues with pagination.

**Comment by bryceadams** [comment] 2020-07-03 00:35
Hi! Do you have more info or an example of an issue with pagination caused by this specifically?

**Comment by bryceadams** [comment] 2020-07-03 00:37
PS. Feel free to email us directly through support to discuss a specific site / Metorik account.

**Comment by tinydylan** [comment] 2020-07-03 01:03
In addition to being Metorik users, we're using this plugin to identify recently-updated customers/orders/accounts and extract into our corporate data warehouse. 

We don't have a specific issue in practice, just a risk in theory.

If we receive the first page of data, and the underlying data changes before we get the second page, then there's a risk that items will shift from page 2 to page 1, and we'll miss them.

So, say the underlying data has these records, and they come out in this order:
1,2,3,4,5,6,7,8,9,10

Say we're paginating with a page size of 5. We get the first page:

1,2,3,4,5

then the data changes, so that the data now in this order:

1,3,4,5,6,7,8,9,10,2

and we get page 2:

7,8,9,10,2

we've missed item 6.

Sorting by updated date ascending solves this for many cases. 

e.g., if the data - sorted - is like this:
1,2,3,4,5,6,7,8,9,10

we can get the first page:
1,2,3,4,5

then look at item #5 and see when it was last updated. We can then ask for all records updated since that time. So, if item 2 is modified in the meantime, the sort order is:

1,3,4,5,6,7,8,9,10,2

and then we fetch a page of data for things newer than item 5, which would be:

6,7,8,9,10

**Comment by bryceadams** [comment] 2020-07-03 01:04
Good points Dylan, definitely would be better to order by it and remove any possible issues like this. I'll get this added in the next update.

Thanks for the info / example! :)

**Comment by tinydylan** [comment] 2020-07-03 01:06
No worries. And thank you for the lightning-quick responses!

**Comment by bryceadams** [comment] 2020-12-11 10:45
Closing until re-writing endpoints to have better pagination / inherit Woo one. For now would recommend using the limit parameter so pagination isn't need (eg. could set limit 500000).

**Closed by bryceadams** 2020-12-11 10:45 UTC
